WebShop_Demo/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebShop_Demo.DAL;

namespace WebShop_Demo.Models
{
    public class Product
    {
        public bool DataFromDB { get; set; }
        public bool ProductCreated { get; set; }

        public List<WebShop_Demo.DAL.Products> Products { get; set; }
    }
}

WebShop_Demo/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebShop_Demo.Controllers
{
    public class MainController : Controller
    {
        // GET: Main
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebShop_Demo/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShop_Demo.DAL;
using WebShop_Demo.Models;
using WebShop_Demo.Repository;

namespace WebShop_Demo.Controllers
{
    public class ProductsController : Controller
    {
        private GenericUnit _unitOfWork = new GenericUnit();
        private Product productList = new Product();

        [HttpGet]
        public ActionResult Products()
        {
            productList.Products = GetProductFromDB();

            //Add data in memory
            if (System.Web.HttpContext.Current.Cache["product"] == null)
            {
                System.Web.HttpContext.Current.Cache["product"] = productList.Products;
            }

            return View(productList);
        }

        [HttpPost]
        public ActionResult Products(Product product)
        {
            bool Cache = product.DataFromDB;
            ModelState.Clear();

            if (Cache)
            {
                product.Products = ((List<WebShop_Demo.DAL.Products>)System.Web.HttpContext.Current.Cache["product"]);
            }
            else
            {
                product.Products = GetProductFromDB();
            }

            return View(product);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Create(WebShop_Demo.DAL.Products product)
        {
            ViewBag.ErrorMessage = "";

            int lastRowID = GetLastRowIdFromDB();

            product.RowId = lastRowID +1;
            product.CategoryId = 1;
            product.Created = DateTime.Now;
            product.LastModified = DateTime.Now;
            product.Active = true;

            bool rowAdded = AddRowInDB(product);

            if (rowAdded)
            {
                ViewBag.ErrorMessage = "OK";
                ModelState.Clear();
                product = new Products();
            }
            else
            {
                ViewBag.ErrorMessage = "Error";
            }

            return View(product);
        }


        //Obtain Data from DB
        private List<WebShop_Demo.DAL.Products> GetProductFromDB()
        {
            List<WebShop_Demo.DAL.Products> products =
                _unitOfWork.GetInstanceRepository<WebShop_Demo.DAL.Products>()
                    .GetAllRowsIQueryable()
                    .OrderBy(i => i.ProductId)
                    .ToList();

            return products;
        }

        //Obtain Last RowID from DB
        private int GetLastRowIdFromDB()
        {
            productList.Products = GetProductFromDB();
            int lastRowId = productList.Products.Max(i => i.RowId);
            return lastRowId;
        }

        //Add row in DB 
        private bool AddRowInDB(WebShop_Demo.DAL.Products product)
        {
            _unitOfWork.GetInstanceRepository<WebShop_Demo.DAL.Products>().Add(product);
            int row = _unitOfWork.SaveChanges();
            if (row == 0) return true;
            return false;
        }

    }
}

WebShop_Demo/Views/Main/Index.cshtml

@{
    ViewBag.Title = "WebShop";
}

<h2>WebShop</h2>

@DateTime.Now.ToString()


WebShop_Demo/Views/Main/Products.cshtml
@model IEnumerable<WebShop_Demo.DAL.Products>

@{
    ViewBag.Title = "Products";
}

<h2>Products</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RowId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastModified)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categories.CategoryName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RowId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastModified)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Active)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categories.CategoryName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProductId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProductId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProductId })
        </td>
    </tr>
}

</table>

WebShop_Demo/Views/Products/Create.cshtml
@model WebShop_Demo.DAL.Products

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Products", FormMethod.Post))
{
    @*<input type="hidden" value="@message" id="hd_message"/>*@
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Products</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.RowId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RowId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RowId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.LastModified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastModified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastModified, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" id="createProduct" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Products")
</div>


@if (ViewBag.ErrorMessage == "OK")
{
    <script type="text/javascript">
        alert("Product Created!!");
    </script>
}

@if (ViewBag.ErrorMessage == "Error")
{
    <script type="text/javascript">
        alert("Error!!! Product Id Invalid.");
    </script>
}

WebShop_Demo/Views/Products/Products.cshtml
@model WebShop_Demo.Models.Product

@{
    ViewBag.Title = "Products";
}

@using (Html.BeginForm("Products", "Products", FormMethod.Post))
{
    <h2>Products</h2>

    <div>
        Data from Memory @Html.CheckBoxFor(model => model.DataFromDB) 
        <input type="submit" value="Reload"/>
    </div>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>

    <table class="table">
        <tr>
            <th>
                Product Id
            </th>
            <th>
                Product Name
            </th>
            <th>
                Description
            </th>
            <th>
                Active
            </th>
            <th>
                Price
            </th>
            <th>
                Category Name
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Products)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Active)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categories.CategoryName)
                </td>
            </tr>
        }

    </table>
}

WebShop_Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WebShop", "Index", "Main", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Products", "Products", "Products", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Miguel Jimenez - jimenez555@gmail.com</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>